defaults:
  - model: default
  - trainer: default

seed: 42

data:
  batch_size: 32
  num_workers: 6

model:
  name: fusion
  lr: 1e-3

trainer:
  max_epochs: 30
  gpus: 1

wandb:
  project: danger-ai
  entity: your-wandb-entity

neptune:
  enabled: false
  project: "<org>/<project>"
