org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dkotlin.incremental=false -Dkotlin.daemon.enabled=false -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental.useClasspathSnapshot=false
kotlin.incremental=false
kotlin.daemon.enabled=false
kotlin.compiler.execution.strategy=in-process
kotlin.incremental.useClasspathSnapshot=false
android.useAndroidX=true
android.enableJetifier=true
